### ISSUE TITLE
Make leave site work as expected

### ISSUE THREAD

**Issue by shiqimei** [markboard-io/markboard#19]
![image](https://user-images.githubusercontent.com/32427260/226423298-03219ce0-f131-4cae-88c6-b275437ac183.png)

If changes were saved to mongoDB, it shouldn't prompt this message.

**Comment by raazseth** [comment]
Can you assign me this issue @shiqimei @ccbond

**Comment by shiqimei** [comment]
Sure!

**Comment by shiqimei** [comment]
Hi, @raazseth. Are you still working on this?

**Comment by shiqimei** [comment]
Fixed via 070d3c3258ad605be8991fd0675680bcea626742
